### ISSUE TITLE
Error when getting all texts from WaitRoom widget

### ISSUE THREAD

**Issue by ewenw** [nodeGame/nodegame-widgets#18] opened 2017-10-23 05:58 UTC
When calling node.widgets.instances[0].getAllTexts() on the WaitRoom screen, the following error occurs:
`nodegame-full.js:50764 Uncaught TypeError: Cannot read property 'nGames' of undefined
    at tooManyPlayers (nodegame-full.js:50764)
    at strGetter (nodegame-full.js:37784)
    at WaitingRoom.Widget.getText (nodegame-full.js:37707)
    at strGetterMulti (nodegame-full.js:37827)
    at WaitingRoom.Widget.getAllTexts (nodegame-full.js:37750)
    at <anonymous>:1:27`
Any ideas on how to fix this? @shakty

**Comment by shakty** [comment] 2017-10-23 19:21
Hi, yes this is a duplicate. Some methods are expecting a parameter that should be passed, and are throwing an error. Check the other issue, and let me know if you need more explanations.

Duplicate of #16

**Closed by shakty** 2017-10-23 19:21 UTC
